#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path


CHAPTER_DIR_RE = re.compile(r"chapter\d+$")
FENCE_RE = re.compile(r"^\s*```")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*\S)\s*$")
PRINT_PAGE_NAME = "print_page.md"


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def clean_heading(text: str) -> str:
    return re.sub(r"\s+#+\s*$", "", text).strip()


def first_heading_title(path: Path) -> str:
    in_code = False

    for line in path.read_text(encoding="utf-8").splitlines():
        if FENCE_RE.match(line):
            in_code = not in_code
            continue

        if in_code:
            continue

        match = HEADING_RE.match(line)
        if match:
            return clean_heading(match.group(2))

    return path.stem


def nav_path(docs_dir: Path, page: Path) -> str:
    return page.relative_to(docs_dir).as_posix()


def append_page(lines: list[str], docs_dir: Path, page: Path, indent: str = "  ") -> None:
    title = first_heading_title(page)
    lines.append(f"{indent}- {yaml_string(title)}: {yaml_string(nav_path(docs_dir, page))}\n")


def append_chapter(lines: list[str], docs_dir: Path, chapter_dir: Path) -> None:
    index_page = chapter_dir / "index.md"
    if not index_page.exists():
        return

    chapter_title = first_heading_title(index_page)
    lines.append(f"  - {yaml_string(chapter_title)}:\n")
    append_page(lines, docs_dir, index_page, indent="    ")

    for page in sorted(chapter_dir.glob("*.md")):
        if page.name == "index.md":
            continue
        append_page(lines, docs_dir, page, indent="    ")


def write_config(docs_dir: Path, base_config: Path, output_config: Path) -> None:
    inherit_path = os.path.relpath(base_config, output_config.parent)
    lines = [
        "# Generated by build-site.sh. Do not edit by hand.\n",
        f"INHERIT: {yaml_string(inherit_path)}\n",
        "\n",
        "nav:\n",
    ]

    for page in sorted(docs_dir.glob("*.md")):
        if page.name in ("index.md", PRINT_PAGE_NAME):
            continue
        append_page(lines, docs_dir, page)

    for chapter_dir in sorted(docs_dir.iterdir()):
        if chapter_dir.is_dir() and CHAPTER_DIR_RE.fullmatch(chapter_dir.name):
            append_chapter(lines, docs_dir, chapter_dir)

    output_config.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "Usage: generate_mkdocs_config.py <docs_dir> <base_config> <output_config>",
            file=sys.stderr,
        )
        return 2

    docs_dir = Path(sys.argv[1])
    base_config = Path(sys.argv[2])
    output_config = Path(sys.argv[3])

    if not docs_dir.is_dir():
        print(f"Docs directory not found: {docs_dir}", file=sys.stderr)
        return 1

    if not base_config.is_file():
        print(f"Base config not found: {base_config}", file=sys.stderr)
        return 1

    write_config(docs_dir, base_config, output_config)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
