#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path


CHAPTER_DIR_RE = re.compile(r"chapter\d+$")
FENCE_RE = re.compile(r"^\s*```")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*\S)\s*$")
PRINT_PAGE_NAME = "print_page.md"
SECTION_TITLES = {
    "basic": "基礎編",
    "practice": "実践編",
}


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def clean_heading(text: str) -> str:
    return re.sub(r"\s+#+\s*$", "", text).strip()


def first_heading_title(path: Path) -> str:
    in_code = False

    for line in path.read_text(encoding="utf-8").splitlines():
        if FENCE_RE.match(line):
            in_code = not in_code
            continue

        if in_code:
            continue

        match = HEADING_RE.match(line)
        if match:
            return clean_heading(match.group(2))

    return path.stem


def nav_path(docs_dir: Path, page: Path) -> str:
    return page.relative_to(docs_dir).as_posix()


def append_page(lines: list[str], docs_dir: Path, page: Path, indent: str = "  ") -> None:
    title = first_heading_title(page)
    lines.append(f"{indent}- {yaml_string(title)}: {yaml_string(nav_path(docs_dir, page))}\n")


def append_chapter(lines: list[str], docs_dir: Path, chapter_dir: Path, indent: str = "  ") -> None:
    index_page = chapter_dir / "index.md"
    if not index_page.exists():
        return

    chapter_title = first_heading_title(index_page)
    child_indent = indent + "  "
    lines.append(f"{indent}- {yaml_string(chapter_title)}:\n")
    append_page(lines, docs_dir, index_page, indent=child_indent)

    for page in sorted(chapter_dir.glob("*.md")):
        if page.name == "index.md":
            continue
        append_page(lines, docs_dir, page, indent=child_indent)


def append_nav_snippet(lines: list[str], path: Path, label: str) -> None:
    if not path.is_file():
        return

    text = path.read_text(encoding="utf-8").strip("\n")
    if not text.strip():
        return

    lines.append(f"  # {label}: {path.as_posix()}\n")
    for line in text.splitlines():
        if line.strip():
            lines.append(f"  {line.rstrip()}\n")
        else:
            lines.append("\n")


def chapter_dirs(parent: Path) -> list[Path]:
    return [
        item
        for item in sorted(parent.iterdir())
        if item.is_dir() and CHAPTER_DIR_RE.fullmatch(item.name)
    ]


def section_title(path: Path) -> str:
    if path.name in SECTION_TITLES:
        return SECTION_TITLES[path.name]
    return path.name.replace("-", " ").replace("_", " ").title()


def append_generated_chapters(lines: list[str], docs_dir: Path) -> None:
    lines.append("  # Generated from LeanMathNote/**/*.lean\n")

    for chapter_dir in chapter_dirs(docs_dir):
        append_chapter(lines, docs_dir, chapter_dir)

    for section_dir in sorted(docs_dir.iterdir()):
        if not section_dir.is_dir():
            continue
        chapters = chapter_dirs(section_dir)
        if not chapters:
            continue

        lines.append(f"  - {yaml_string(section_title(section_dir))}:\n")
        section_index = section_dir / "index.md"
        if section_index.exists():
            append_page(lines, docs_dir, section_index, indent="    ")

        for chapter_dir in chapters:
            append_chapter(lines, docs_dir, chapter_dir, indent="    ")


def write_config(
    docs_dir: Path,
    base_config: Path,
    output_config: Path,
    nav_before: Path | None = None,
    nav_after: Path | None = None,
) -> None:
    inherit_path = os.path.relpath(base_config, output_config.parent)
    lines = [
        "# Generated by scripts/build-site.sh. Do not edit by hand.\n",
        f"INHERIT: {yaml_string(inherit_path)}\n",
        "\n",
        "nav:\n",
    ]

    if nav_before is not None:
        append_nav_snippet(lines, nav_before, "Manual nav before generated chapters")

    append_generated_chapters(lines, docs_dir)

    if nav_after is not None:
        append_nav_snippet(lines, nav_after, "Manual nav after generated chapters")

    output_config.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    if len(sys.argv) not in (4, 5, 6):
        print(
            "Usage: generate_mkdocs_config.py <docs_dir> <base_config> <output_config> [nav_before] [nav_after]",
            file=sys.stderr,
        )
        return 2

    docs_dir = Path(sys.argv[1])
    base_config = Path(sys.argv[2])
    output_config = Path(sys.argv[3])
    nav_before = Path(sys.argv[4]) if len(sys.argv) >= 5 and sys.argv[4] else None
    nav_after = Path(sys.argv[5]) if len(sys.argv) >= 6 and sys.argv[5] else None

    if not docs_dir.is_dir():
        print(f"Docs directory not found: {docs_dir}", file=sys.stderr)
        return 1

    if not base_config.is_file():
        print(f"Base config not found: {base_config}", file=sys.stderr)
        return 1

    write_config(docs_dir, base_config, output_config, nav_before, nav_after)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
