#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path


CHAPTER_DIR_RE = re.compile(r"chapter\d+$")


def read_page(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def chapter_dirs(parent: Path) -> list[Path]:
    return [
        item
        for item in sorted(parent.iterdir())
        if item.is_dir() and CHAPTER_DIR_RE.fullmatch(item.name)
    ]


def append_chapter_pages(pages: list[Path], chapter_dir: Path) -> None:
    chapter_index = chapter_dir / "index.md"
    if chapter_index.exists():
        pages.append(chapter_index)

    for page in sorted(chapter_dir.glob("*.md")):
        if page.name == "index.md":
            continue
        pages.append(page)


def collect_pages(pages_dir: Path, output_path: Path) -> list[Path]:
    pages: list[Path] = []
    root_index = pages_dir / "index.md"

    if root_index.exists():
        pages.append(root_index)

    for chapter_dir in chapter_dirs(pages_dir):
        append_chapter_pages(pages, chapter_dir)

    for section_dir in sorted(pages_dir.iterdir()):
        if not section_dir.is_dir():
            continue
        chapters = chapter_dirs(section_dir)
        if not chapters:
            continue

        for chapter_dir in chapters:
            append_chapter_pages(pages, chapter_dir)

    return [page for page in pages if page != output_path]


def write_print_page(pages_dir: Path, output_path: Path) -> None:
    pages = collect_pages(pages_dir, output_path)
    if not pages:
        raise ValueError(f"No pages found in {pages_dir}")

    parts = [
        "<!-- Generated by scripts/generate_print_page.py. Do not edit by hand. -->",
        "",
        '<div class="print-page" markdown="1">',
        "",
    ]

    for page in pages:
        content = read_page(page)
        if not content:
            continue
        parts.append(content)
        parts.append("")

    parts.append("</div>")

    output_path.write_text("\n\n".join(parts).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    if len(sys.argv) not in (2, 3):
        print(
            "Usage: generate_print_page.py <pages_dir> [output_name]",
            file=sys.stderr,
        )
        return 2

    pages_dir = Path(sys.argv[1])
    output_name = sys.argv[2] if len(sys.argv) == 3 else "print_page.md"
    output_path = pages_dir / output_name

    if not pages_dir.is_dir():
        print(f"Pages directory not found: {pages_dir}", file=sys.stderr)
        return 1

    write_print_page(pages_dir, output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
